"""
Shared data models for the RAG guidance pipeline.

All pipeline stages exchange these types. Pydantic models are used for anything
that crosses an API boundary (metadata sent to Vertex AI Search); plain dataclasses
are used for in-process pipeline state.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Metadata (Pydantic — crosses GCP API boundary)
# ---------------------------------------------------------------------------


class ChunkMetadata(BaseModel):
    """Per-chunk metadata generated by Gemini and stored in Vertex AI Search.

    All fields correspond to filterable schema attributes registered in the
    DataStore via scripts/setup_vertex_search.py. Schema changes require a
    full re-import — see issues.md P3.
    """

    doc_id: str = Field(description="SHA-256 hex digest of the source PDF bytes")
    source_file: str = Field(description="Original filename (basename only)")
    title: str = Field(default="", description="Inferred document or chapter title")
    domain: str = Field(
        default="",
        description="Controlled-vocabulary specialty domain (e.g. cardiology, oncology)",
    )
    subdomain: str = Field(default="", description="Narrower topic within the domain")
    doc_type: str = Field(
        default="",
        description="textbook | clinical_guideline | research_paper | front_matter",
    )
    chapter: str = Field(default="", description="Nearest detected chapter or section name")
    page_start: int = Field(default=0, description="First page of chunk (1-indexed)")
    page_end: int = Field(default=0, description="Last page of chunk (1-indexed)")
    chunk_index: int = Field(default=0, description="Sequential index within the document")
    keywords: list[str] = Field(default_factory=list, description="Key terms extracted by Gemini")
    entities: list[str] = Field(
        default_factory=list,
        description="Named clinical/scientific entities (drugs, conditions, genes, etc.)",
    )
    evidence_level: Optional[str] = Field(
        default=None,
        description="GRADE evidence level if applicable: A | B | C | D",
    )
    year_published: Optional[int] = Field(
        default=None,
        description="Publication year; None if not extractable",
    )


# ---------------------------------------------------------------------------
# Extraction (dataclasses — internal pipeline state)
# ---------------------------------------------------------------------------


@dataclass
class Page:
    """A single extracted page from a PDF."""

    page_num: int
    text: str
    tables: list[dict] = field(default_factory=list)
    # Each table: {"rows": [["cell", ...], ...], "bbox": (x0, y0, x1, y1)}
    has_figures: bool = False


@dataclass
class ExtractedDocument:
    """Complete output of the PDF extraction stage."""

    doc_id: str
    source_file: str
    source_path: str
    pages: list[Page] = field(default_factory=list)
    extraction_method: str = "pdfplumber"  # "pdfplumber" | "document_ai"


# ---------------------------------------------------------------------------
# Chunking
# ---------------------------------------------------------------------------


@dataclass
class Chunk:
    """A single semantically coherent text segment ready for indexing."""

    chunk_id: str           # Canonical form: "{doc_id}_{chunk_index:05d}"
    doc_id: str
    text: str
    page_start: int
    page_end: int
    chunk_index: int
    parent_section: str     # Nearest detected section header above this chunk
    metadata: Optional[ChunkMetadata] = None


# ---------------------------------------------------------------------------
# Retrieval
# ---------------------------------------------------------------------------


@dataclass
class SearchResult:
    """A single result returned by Vertex AI Search."""

    chunk_id: str
    doc_id: str
    text: str
    score: float
    metadata: Optional[ChunkMetadata] = None


# ---------------------------------------------------------------------------
# Generation / Citations
# ---------------------------------------------------------------------------


@dataclass
class Attribution:
    """Maps a span of generated text back to a retrieved source chunk.

    Populated from Vertex AI grounding metadata. The mapping is approximate —
    see caveats.md §2 (Citation Accuracy).
    """

    segment_text: str       # Portion of the generated response this attribution covers
    source_chunk_id: str
    source_doc_id: str
    confidence: float = 1.0


@dataclass
class Citation:
    """A formatted, user-facing citation for a retrieved source."""

    number: int             # [1], [2], ... reference number in the response text
    source_file: str
    title: str
    chapter: str
    page_start: int
    page_end: int
    chunk_id: str


@dataclass
class GeneratedResponse:
    """Final output of the end-to-end RAG pipeline for a single query."""

    text: str                                           # Response with inline [n] citation markers
    citations: list[Citation] = field(default_factory=list)
    attributions: list[Attribution] = field(default_factory=list)
    domain: str = ""
    query: str = ""


# ---------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------


@dataclass
class ImportResult:
    """Result of a Vertex AI Search async import operation."""

    operation_name: str
    success_count: int = 0
    failure_count: int = 0
    errors: list[str] = field(default_factory=list)
    completed: bool = False
