"""
Shared data models for the RAG guidance pipeline.

All pipeline stages exchange these types. Pydantic models are used for anything
that crosses an API boundary (metadata sent to Vertex AI Search); plain dataclasses
are used for in-process pipeline state.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Metadata (Pydantic — crosses GCP API boundary)
# ---------------------------------------------------------------------------


class ChunkMetadata(BaseModel):
    """Per-chunk metadata generated by Gemini and stored in Vertex AI Search.

    Field names, enums, and defaults mirror ``config/metadata_schema.json`` —
    the authoritative psychotherapy (RTA + ASA) schema. That JSON file is the
    single source of truth for the controlled vocabulary; ``ingestion``
    validates against it via ``config.schema_loader.SchemaVocabulary``. Keep
    this model in sync with the schema: fields registered here are the ones
    serialized to ``structData`` and registered as filterable DataStore
    attributes via ``scripts/setup_vertex_search.py``. Schema changes require a
    purge + full re-import — see issues.md P3 and the schema ``notes`` block.

    Only ``doc_id`` is strictly required; every other field carries a
    schema-aligned default so that ``_fallback_extraction`` never hard-fails
    when Gemini output is unavailable.
    """

    # --- Provenance / identity -------------------------------------------
    doc_id: str = Field(description="SHA-256 hex digest of the source PDF bytes")
    source_file: str = Field(default="", description="Original filename (basename only)")
    title: str = Field(default="", description="Inferred document or chapter title")
    chapter: str = Field(default="", description="Nearest chapter/session heading above the chunk")
    page_start: int = Field(default=0, description="First page of chunk (1-indexed)")
    page_end: int = Field(default=0, description="Last page of chunk (1-indexed)")
    chunk_index: int = Field(default=0, description="Sequential index within the document")
    year_published: Optional[int] = Field(
        default=None, description="Publication year; None if not extractable"
    )

    # --- Orientation / classification ------------------------------------
    domain: str = Field(
        default="other",
        description="Document-level orientation (e.g. cognitive_behavioral, dialectical_behavior)",
    )
    subdomain: str = Field(default="", description="Narrower topic within the domain (free text)")
    doc_type: str = Field(
        default="",
        description="treatment_manual | session_transcript | rct_paper | front_matter | ...",
    )

    # --- Clinical content (chunk-level) ----------------------------------
    therapeutic_modality: list[str] = Field(
        default_factory=list, description="Therapy modalities this passage addresses (CBT, DBT, ...)"
    )
    clinical_presentation: list[str] = Field(
        default_factory=list, description="Diagnostic themes addressed (depression, PTSD, BPD, ...)"
    )
    session_event_tags: list[str] = Field(
        default_factory=lambda: ["none"],
        description="In-session event types (primary RTA retrieval trigger)",
    )
    session_phase: str = Field(default="any", description="Point in the treatment arc this applies to")
    target_audience: str = Field(
        default="therapist", description="therapist | trainee | supervisor | patient | general"
    )
    technique_tags: list[str] = Field(
        default_factory=list, description="Named clinical techniques (chain analysis, PE, ...)"
    )
    keywords: list[str] = Field(default_factory=list, description="Key topic terms extracted by Gemini")
    clinical_caution: list[str] = Field(
        default_factory=list, description="Explicit contraindications/precautions stated in the chunk"
    )
    practice_recommendation_level: Optional[str] = Field(
        default=None, description="Strength/polarity of the practice recommendation (replaces GRADE)"
    )
    training_level_required: Optional[str] = Field(
        default=None, description="Minimum clinician training level for the technique(s)"
    )
    risk_dimension_tags: list[str] = Field(
        default_factory=list, description="Ongoing risk-monitoring dimensions this chunk addresses"
    )

    # --- Retrieval routing ------------------------------------------------
    corpus_scope: str = Field(
        default="rta_and_asa",
        description="Hard routing field: rta_and_asa | asa_only (asa_only excluded from RTA)",
    )
    analysis_function: list[str] = Field(
        default_factory=list, description="Post-session (ASA) analysis function(s) this chunk serves"
    )

    # --- Evidence / population (chunk-level) ------------------------------
    evidence_base: str = Field(
        default="not_applicable", description="Epistemological type of the chunk's evidence"
    )
    patient_population: list[str] = Field(
        default_factory=lambda: ["not_specified"],
        description="Population the chunk's evidence/recommendation applies to",
    )
    time_horizon: str = Field(default="any", description="Temporal scope of clinical relevance")
    outcome_measure_tags: list[str] = Field(
        default_factory=list, description="Outcome instruments referenced (PHQ-9, GAD-7, ...)"
    )

    # --- Source-level provenance / representation -------------------------
    population_focus: list[str] = Field(
        default_factory=lambda: ["not_reported"],
        description="Population the source was developed/validated for",
    )
    source_language: list[str] = Field(
        default_factory=lambda: ["English"], description="Language(s) of the source and adaptations"
    )
    setting: list[str] = Field(
        default_factory=lambda: ["not_reported"], description="Setting(s) the source was developed/tested in"
    )
    adaptation_status: str = Field(
        default="standard", description="standard | culturally_adapted | resource_constrained | translated"
    )
    missingness: list[str] = Field(
        default_factory=list, description="What the source does not report (informational only)"
    )
    presentation_coverage: list[str] = Field(
        default_factory=lambda: ["none_reported"],
        description="Cultural/somatic/relational framings the source covers",
    )
    study_type: Optional[str] = Field(default=None, description="Overall study design of the source")
    sample_size: Optional[int] = Field(default=None, description="Total study sample size, where applicable")
    intended_use_context: list[str] = Field(
        default_factory=list, description="High-level intended use context (in_session_support, ...)"
    )


# ---------------------------------------------------------------------------
# Extraction (dataclasses — internal pipeline state)
# ---------------------------------------------------------------------------


@dataclass
class Page:
    """A single extracted page from a PDF."""

    page_num: int
    text: str
    tables: list[dict] = field(default_factory=list)
    # Each table: {"rows": [["cell", ...], ...], "bbox": (x0, y0, x1, y1)}
    has_figures: bool = False


@dataclass
class ExtractedDocument:
    """Complete output of the PDF extraction stage."""

    doc_id: str
    source_file: str
    source_path: str
    pages: list[Page] = field(default_factory=list)
    extraction_method: str = "pdfplumber"  # "pdfplumber" | "document_ai"


# ---------------------------------------------------------------------------
# Chunking
# ---------------------------------------------------------------------------


@dataclass
class Chunk:
    """A single semantically coherent text segment ready for indexing."""

    chunk_id: str           # Canonical form: "{doc_id}_{chunk_index:05d}"
    doc_id: str
    text: str
    page_start: int
    page_end: int
    chunk_index: int
    parent_section: str     # Nearest detected section header above this chunk
    metadata: Optional[ChunkMetadata] = None


# ---------------------------------------------------------------------------
# Retrieval
# ---------------------------------------------------------------------------


@dataclass
class SearchResult:
    """A single result returned by Vertex AI Search."""

    chunk_id: str
    doc_id: str
    text: str
    score: float
    metadata: Optional[ChunkMetadata] = None


# ---------------------------------------------------------------------------
# Generation / Citations
# ---------------------------------------------------------------------------


@dataclass
class Attribution:
    """Maps a span of generated text back to a retrieved source chunk.

    Populated from Vertex AI grounding metadata. The mapping is approximate —
    see caveats.md §2 (Citation Accuracy).
    """

    segment_text: str       # Portion of the generated response this attribution covers
    source_chunk_id: str
    source_doc_id: str
    confidence: float = 1.0


@dataclass
class Citation:
    """A formatted, user-facing citation for a retrieved source."""

    number: int             # [1], [2], ... reference number in the response text
    source_file: str
    title: str
    chapter: str
    page_start: int
    page_end: int
    chunk_id: str


@dataclass
class GeneratedResponse:
    """Final output of the end-to-end RAG pipeline for a single query."""

    text: str                                           # Response with inline [n] citation markers
    citations: list[Citation] = field(default_factory=list)
    attributions: list[Attribution] = field(default_factory=list)
    domain: str = ""
    query: str = ""


# ---------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------


@dataclass
class ImportResult:
    """Result of a Vertex AI Search async import operation."""

    operation_name: str
    success_count: int = 0
    failure_count: int = 0
    errors: list[str] = field(default_factory=list)
    completed: bool = False
